FROM clojure:temurin-25-tools-deps-trixie

COPY --from=node:24-trixie-slim /usr/local/bin/node /usr/local/bin/node
COPY --from=node:24-trixie-slim /usr/local/lib/node_modules /usr/local/lib/node_modules

RUN ln -s ../lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm \
  && ln -s ../lib/node_modules/npm/bin/npx-cli.js /usr/local/bin/npx \
  && apt-get update \
  && apt-get install -y --no-install-recommends curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace/apps/web

COPY apps/web/deps.edn /workspace/apps/web/deps.edn
COPY packages/shared/deps.edn /workspace/packages/shared/deps.edn
COPY packages/api-sdk/deps.edn /workspace/packages/api-sdk/deps.edn
COPY packages/ui/deps.edn /workspace/packages/ui/deps.edn
RUN mkdir -p /workspace/packages/shared/src /workspace/packages/api-sdk/src /workspace/packages/ui/src \
  && clojure -A:web -P

COPY apps/web/package.json /workspace/apps/web/package.json
RUN npm install

COPY packages /workspace/packages
COPY apps/web /workspace/apps/web

EXPOSE 8280 9630 9631

CMD ["npx", "shadow-cljs", "watch", "app"]
